### ISSUE TITLE
Define initial data schema for storing entities and links

### ISSUE THREAD

**Issue by CharlieKarafotias** [CharlieKarafotias/tap#4]
- SurrealDB has a lot of unique ways to store data
- This work will be finding the best way to store the relationship of parent-entities to child key/value pairs
- Initial thoughts:
  - Prioritize read over write. What surreal db structure gives us this?
  - Need to query list of parent entities fast for auto complete (`tap --list-parent-entities`)
  - For auto complete, once parent entity is typed in, should be able to get all key names (`tap my-repo --keys`)
 
```yaml
- repo1:
    repo: https://github.com/CharlieKarafotias/tmgr/tree/main
- repo2:
    repo: https://github.com/CharlieKarafotias/tmgr/tree/main
- repo3:
    repo: https://github.com/CharlieKarafotias/tmgr/tree/main
    secrets: https://github.com/CharlieKarafotias/tmgr/tree/main
```
